class Countries {
  static const List<String> listOfCountries = [
    'Österreich',
    'Deutschland',
    'Schweiz',
    'Albanien',
    'Andorra',
    'Belarus',
    'Belgien',
    'Bosnien und Herzegowina',
    'Bulgarien',
    'Dänemark',
    'Estland',
    'Finnland',
    'Frankreich',
    'Griechenland',
    'Irland',
    'Island',
    'Italien',
    'Kosovo',
    'Kroatien',
    'Lettland',
    'Liechtenstein',
    'Litauen',
    'Luxemburg',
    'Malta',
    'Moldawien',
    'Monaco',
    'Montenegro',
    'Niederlande',
    'Nordmazedonien',
    'Norwegen',
    'Polen',
    'Portugal',
    'Rumänien',
    'Russland',
    'San Marino',
    'Schweden',
    'Serbien',
    'Slowakei',
    'Slowenien',
    'Spanien',
    'Tschechien',
    'Türkei',
    'Ukraine',
    'Ungarn',
    'Vatikanstadt',
    'Vereinigtes Königreich',
    'Zypern',
  ];
}
